In [2]:
import os

# Set environment variables
os.environ['CUDA_HOME'] = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
os.environ['CUDA_PATH'] = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
os.environ['PATH'] = os.environ['CUDA_HOME'] + r'\bin;' + os.environ['CUDA_HOME'] + r'\libnvvp;' + os.environ['PATH']

# Verify the environment variables
print('CUDA_HOME:', os.environ['CUDA_HOME'])
print('CUDA_PATH:', os.environ['CUDA_PATH'])
print('PATH:', os.environ['PATH'])

# Verify CUDA version
!nvcc --version

# Verify PyTorch with CUDA
import torch

#print("PyTorch version:", torch.version.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Current device:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")


CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;c:\Users\ebjor\anaconda\envs\ddm3;C:\Users\ebjor\anaconda\envs\ddm3;C:\Users\ebjor\anaconda\envs\ddm3\Library\mingw-w64\bin;C:\Users\ebjor\anaconda\envs\ddm3\Library\usr\bin;C:\Users\ebjor\anaconda\envs\ddm3\Library\bin;C:\Users\ebjor\anaconda\envs\ddm3\Scripts;C:\Users\ebjor\anaconda\envs\ddm3\bin;C:\Users\ebjor\anaconda\condabin;C:\Users\ebjor\anaconda;C:\Users\ebjor\anaconda\Library\mingw-w64\bin;C:\Users\ebjor\anaconda\Library\usr\bin;C:\Users\ebjor\anaconda\Library\bin;C:\Users\ebjor\anaconda\Scripts;C:\Program Files\NVIDIA\CUDNN\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\libnvvp;C:\Program Files\Oculus\Support\oculus-runtime;C:\Window

In [3]:
import torch

In [4]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Current device:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")


PyTorch version: 1.8.0
CUDA available: True
Current device: 0
Device name: NVIDIA GeForce RTX 2070 with Max-Q Design


In [5]:
import os

# Ensure the correct environment variables are set
os.environ['CUDA_HOME'] = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
os.environ['CUDA_PATH'] = r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
os.environ['PATH'] = os.environ['CUDA_HOME'] + r'\bin;' + os.environ['CUDA_HOME'] + r'\libnvvp;' + os.environ['PATH']

# Verify the environment variables
print('CUDA_HOME:', os.environ['CUDA_HOME'])
print('CUDA_PATH:', os.environ['CUDA_PATH'])
print('PATH:', os.environ['PATH'])

# Verify CUDA version
!nvcc --version

# Verify PyTorch with CUDA
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Current device:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")


CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;c:\Users\ebjor\anaconda\envs\ddm3;C:\Users\ebjor\anaconda\envs\ddm3;C:\Users\ebjor\anaconda\envs\ddm3\Library\mingw-w64\bin;C:\Users\ebjor\anaconda\envs\ddm3\Library\usr\bin;C:\Users\ebjor\anaconda\envs\ddm3\Library\bin;C:\Users\ebjor\anaconda\envs\ddm3\Scripts;C:\Users\ebjor\anaconda\envs\ddm3\bin;C:\Users\ebjor\anaconda\condabin;C:\Users\ebjor\anaconda;C:\Users\ebjor\anaconda\Library\mingw-w64\bin;C:\Users\ebjor\anaconda\Library\usr\bin;C:\Users\ebjor\anaconda\Library\bin;C:\Users\ebjor\anaconda\Scripts;C:\Program Files\NVIDIA\CUDNN\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5

In [1]:
from dipy.data import fetch_stanford_hardi, read_stanford_hardi

# Fetch the Stanford HARDI dataset
fetch_stanford_hardi()

# Load the data and gradient table
img, gtab = read_stanford_hardi()

# Extract data and affine from the Nifti image
data = img.get_fdata()
affine = img.affine

print("Data shape:", data.shape)
print("Affine matrix:", affine)


Data shape: (81, 106, 76, 160)
Affine matrix: [[   2.    0.    0.  -80.]
 [   0.    2.    0. -120.]
 [   0.    0.    2.  -60.]
 [   0.    0.    0.    1.]]


In [3]:
import os
dipy_home = os.getenv('DIPY_HOME')
if not dipy_home:
    dipy_home = os.path.expanduser('~/.dipy')
print("DIPY_HOME directory:", dipy_home)

DIPY_HOME directory: C:\Users\ebjor/.dipy


In [4]:
import os

dipy_home = os.getenv('DIPY_HOME')
if not dipy_home:
    dipy_home = os.path.expanduser('~/.dipy')

# List the files in the Stanford HARDI dataset directory
hardi_dir = os.path.join(dipy_home, 'stanford_hardi')
print("Files in Stanford HARDI dataset directory:")
for root, dirs, files in os.walk(hardi_dir):
    for file in files:
        print(os.path.join(root, file))


Files in Stanford HARDI dataset directory:
C:\Users\ebjor/.dipy\stanford_hardi\HARDI150.bval
C:\Users\ebjor/.dipy\stanford_hardi\HARDI150.bvec
C:\Users\ebjor/.dipy\stanford_hardi\HARDI150.nii.gz


In [3]:
!python train_noise_model.py -p train -c config/hardi_150.json


^C
